# Go Linters - GitHub Actions
name: linters
on: [push, pull_request]
jobs:

  # Check linters on latest-ubuntu with default version of Go.
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v3
      with:
        go-version: "1.25"
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Run required linters in .golangci.yml plus hard-coded ones here
      run: make lint
